sudo: true
language: clojure

# https://github.com/technomancy/leiningen/issues/2014#issuecomment-153829977
before_install:
  - yes y | sudo lein upgrade
  - touch ~/.lein/profiles.clj
  - echo '{:user {:plugins [[lein-midje "3.2.1"]]}}' > ~/.lein/profiles.clj
  - lein deps

script:
  # check fails because of "Duplicate Push instruction defined:boolean_and"
  # - lein check
  - lein midje clojush.pushgp.genetic-operators-test
after_success:
  - ./scripts/coveralls.sh
  - ./scripts/after_success.sh 2>&1 | sed "s/$GITHUB_TOKEN/<hidden github token>/"
notifications:
  email: false
